# Compatibility shim — all logic moved to app/classifier/llm/ package.
# This file re-exports everything for backward compatibility.
from app.classifier.llm import (  # noqa: F401
    _BATCH_USER_TEMPLATE,
    _DEFAULT_CATEGORIES,
    _KNOWN_BASE_URLS,
    _SYSTEM,
    _USER_TEMPLATE,
    LLMClassification,
    LLMClient,
    MultiLLMClient,
    Provider,
    _build_pre_extraction_block,
    _extract_json,
    _parse_batch_response,
    _parse_response,
    build_default_providers,
    build_pre_extraction_block,
    build_user_client,
    extract_json,
    get_groq_limiter,
    get_user_client,
    llm_client,
    parse_batch_response,
    parse_response,
    rank_providers,
)

__all__ = [
    "LLMClient",
    "MultiLLMClient",
    "llm_client",
    "LLMClassification",
    "Provider",
    "parse_response",
    "parse_batch_response",
    "extract_json",
    "build_pre_extraction_block",
    "build_user_client",
    "get_user_client",
    "_parse_response",
    "_parse_batch_response",
    "_extract_json",
    "_build_pre_extraction_block",
    "_SYSTEM",
    "_USER_TEMPLATE",
    "_BATCH_USER_TEMPLATE",
    "_DEFAULT_CATEGORIES",
    "_KNOWN_BASE_URLS",
]
