#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# MoneyFlow — local setup script
# One-command bootstrap for a fully self-contained local deployment using
# SQLite + in-memory queue + local auth (no Google OAuth / Gmail / Redis /
# PostgreSQL required).
#
# Usage:
#   chmod +x scripts/setup-local.sh && ./scripts/setup-local.sh
#
# Or from the project root:
#   bash scripts/setup-local.sh
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_DIR"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          MoneyFlow — Local Setup                            ║"
echo "║  Your data stays on this machine. No external services.     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── 1. Check prerequisites ──────────────────────────────────────────────────

echo "🔍 Checking prerequisites..."

PYTHON=""
for candidate in python3 python; do
    if command -v "$candidate" &>/dev/null; then
        VER="$($candidate --version 2>&1 | grep -oP '\d+\.\d+')"
        MAJOR="${VER%.*}"
        MINOR="${VER#*.}"
        if [ "$MAJOR" -ge 3 ] && [ "$MINOR" -ge 11 ]; then
            PYTHON="$candidate"
            echo "   ✓ Python $VER found: $PYTHON"
            break
        fi
    fi
done
if [ -z "$PYTHON" ]; then
    echo "   ✗ Python 3.11+ required. Install it and try again."
    exit 1
fi

NODE=""
for candidate in node nodejs; do
    if command -v "$candidate" &>/dev/null; then
        NODE="$candidate"
        echo "   ✓ Node.js found: $NODE"
        break
    fi
done
if [ -z "$NODE" ]; then
    echo "   ⚠ Node.js not found — frontend build will be skipped."
    echo "     Install Node.js (https://nodejs.org) for hot-reload JSX editing."
    echo "     The pre-built dist/ files are included and will work."
fi

# ── 2. Create .env if missing ───────────────────────────────────────────────

if [ -f ".env" ]; then
    echo ""
    echo "⚠  .env already exists — keeping your configuration."
    echo "   Remove .env and re-run to regenerate."
else
    echo ""
    echo "📝 Creating .env for local mode..."

    SECRET_KEY="sk-$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
    FERNET_KEY="$("$PYTHON" -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || echo "")"

    cat > ".env" <<ENVEOF
# ──────────────────────────────────────────────────────────────────────────────
# MoneyFlow — LOCAL MODE configuration
# Auto-generated by scripts/setup-local.sh
# ──────────────────────────────────────────────────────────────────────────────

# Local mode: uses SQLite + in-memory queue + local auth.
# No Google OAuth, Gmail, PostgreSQL, or Redis required.
LOCAL_MODE=true

# SQLite database — stored in ./data/expense.db
DATABASE_URL=sqlite+aiosqlite:///./data/expense.db

# Auto-generated secrets (do not share)
SECRET_KEY=${SECRET_KEY}
FERNET_KEY=${FERNET_KEY}

# Optional: bring your own LLM API key for AI classification.
# Get a Gemini key for free: https://aistudio.google.com/apikey
# GOOGLE_AI_API_KEY=your-gemini-api-key
ENVEOF
    echo "   ✓ .env created with LOCAL_MODE=true, SQLite, auto-generated secrets"
fi

# ── 3. Create data directory ─────────────────────────────────────────────────

mkdir -p data

# ── 4. Python virtual environment ───────────────────────────────────────────

if [ -d ".venv" ]; then
    echo ""
    echo "📦 Using existing virtual environment (.venv)"
else
    echo ""
    echo "📦 Creating Python virtual environment..."
    "$PYTHON" -m venv .venv
    echo "   ✓ .venv created"
fi

# shellcheck disable=SC1091
source .venv/bin/activate

echo ""
echo "📦 Installing Python dependencies..."
pip install -q --upgrade pip
pip install -q -r requirements.txt
echo "   ✓ Dependencies installed"

# ── 5. Run database migrations ───────────────────────────────────────────────

echo ""
echo "🗄️  Running database migrations..."
alembic upgrade head
echo "   ✓ Migrations applied"

# ── 6. Build frontend ───────────────────────────────────────────────────────

if [ -n "$NODE" ]; then
    # Install npm deps if package.json exists and node_modules is missing
    if [ -f "package.json" ] && [ ! -d "node_modules" ]; then
        echo ""
        echo "📦 Installing npm dependencies..."
        npm install --silent 2>/dev/null || true
    fi

    echo ""
    echo "🔨 Building frontend..."
    # Try the build script, fall back to checking if dist exists
    if [ -f "scripts/build-frontend.mjs" ]; then
        node scripts/build-frontend.mjs 2>/dev/null && echo "   ✓ Frontend built" || echo "   ⚠ Frontend build skipped (using pre-built dist/)"
    else
        echo "   ✓ Using pre-built dist/ files"
    fi
else
    echo ""
    echo "🔨 Skipping frontend build (Node.js not available)"
    echo "   Using pre-built dist/ files"
fi

# ── 7. Done ─────────────────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                     Setup Complete!                         ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                              ║"
echo "║  Start MoneyFlow (no Docker):                                ║"
echo "║    source .venv/bin/activate                                 ║"
echo "║    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000  ║"
echo "║                                                              ║"
echo "║  Start MoneyFlow (Docker):                                   ║"
echo "║    docker compose -f docker-compose.local.yml up --build     ║"
echo "║                                                              ║"
echo "║  Open: http://localhost:8000                                 ║"
echo "║  Click \"Start locally\" to login                              ║"
echo "║                                                              ║"
echo "║  📌 Your data directory: ./data/                             ║"
echo "║  📌 Environment config: .env                                 ║"
echo "║  📌 Database: SQLite (./data/expense.db)                     ║"
echo "║  📌 No external services needed                              ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
